#pragma once

#ifndef OSCI_PREMIUM
#define OSCI_PREMIUM 0
#endif

#ifndef OSCI_PROPRIETARY_BUILD
#define OSCI_PROPRIETARY_BUILD 0
#endif

#ifndef OSCI_GUI_ENABLE_VISUALISER
#define OSCI_GUI_ENABLE_VISUALISER 0
#endif

#ifndef OSCI_GUI_ENABLE_CHOWDSP_RESAMPLING
#define OSCI_GUI_ENABLE_CHOWDSP_RESAMPLING 0
#endif

#if OSCI_PROPRIETARY_BUILD && OSCI_GUI_ENABLE_CHOWDSP_RESAMPLING
#error "OSCI_GUI_ENABLE_CHOWDSP_RESAMPLING cannot be enabled in OSCI_PROPRIETARY_BUILD."
#endif

#ifndef OSCI_GUI_ENABLE_ADVANCED_VISUALISER_FEATURES
#define OSCI_GUI_ENABLE_ADVANCED_VISUALISER_FEATURES OSCI_PREMIUM
#endif
